name: FoliaBack
version: '1.0-SNAPSHOT'
main: me.thecatisbest.foliaback.FoliaBack
api-version: '1.21'
folia-supported: true
commands:
  foliaback:
    description: Back to last location
    usage: /<command>
    aliases: [back]
